### ISSUE TITLE
`cdk list` fails

### ISSUE THREAD

**Issue by delilahlah** [aws-samples/mac1-eks-jenkins#6]
I can't get the example to run locally after following the steps outlined in the README.

```
➜ node --version
v15.5.1
➜ cdk list      

/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/ec2-stack.ts:5:10 - error TS2303: Circular definition of import alias 'EksProps'.

5 import { EksProps } from './ec2-stack';
           ~~~~~~~~
lib/ec2-stack.ts:5:10 - error TS2459: Module '"./ec2-stack"' declares 'EksProps' locally, but it is not exported.

5 import { EksProps } from './ec2-stack';
           ~~~~~~~~

  lib/ec2-stack.ts:5:10
    5 import { EksProps } from './ec2-stack';
               ~~~~~~~~
    'EksProps' is declared here.

    at createTSError (/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/home/[redacted]/build/mac1-eks-jenkins/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
npm ERR! code 1
npm ERR! path /home/[redacted]/build/mac1-eks-jenkins
npm ERR! command failed
npm ERR! command sh -c ts-node "bin/cdk-jenkins.ts"
Subprocess exited with error 1
```

**Comment by pauljrob** [comment]
Will take a look, standby.

**Comment by pauljrob** [comment]
Resolved, please clone the latest repo.
